<?php
function get_dutch( $s, $prefix, $separator, $suffix ) {
    $alph = array(
        'A' => 'Anton',
        'B' => 'Bernard',
        'C' => 'Cornelis',
        'D' => 'Dirk',
        'E' => 'Eduard',
        'F' => 'Ferdinand',
        'G' => 'Gerard',
        'H' => 'Hendrik',
        'I' => 'Izaak',
        'J' => 'Johannes',
        'K' => 'Karel',
        'L' => 'Leo',
        'M' => 'Maria',
        'N' => 'Nico',
        'O' => 'Otto',
        'P' => 'Pieter',
        'Q' => 'Quirinus',
        'R' => 'Rudolf',
        'S' => 'Simon',
        'T' => 'Theodoor',
        'U' => 'Utrecht',
        'V' => 'Victor',
        'W' => 'Willem',
        'X' => 'Xantippe',
        'Y' => 'Ypsilon',
        'Z' => 'Zacharias',
        
        '0' => 'Nul',
        '1' => 'Een',
        '2' => 'Twee',
        '3' => 'Drie',
        '4' => 'Vier',
        '5' => 'Vijf',
        '6' => 'Zes',
        '7' => 'Zeven',
        '8' => 'Acht',
        '9' => 'Negen',
        
        ' ' => 'spatie',
        '.' => 'punt',
        ',' => 'komma',
        ';' => 'puntkomma',
        ':' => 'dubbelepunt',
        '?' => 'vraagteken',
        '!' => 'uitroepteken',
        '@' => 'apenstaartje',
        '&' => 'ampersand',
        '"' => 'dubble aanhalingstekens',
        "'" => 'apostrof',
        '-' => 'koppelteken',
        '/' => 'schuine streep',
        '\\' => 'backslash',
        '(' => 'rond haakje links',
        ')' => 'rond haakje rechts',
        '[' => 'vierkant haakje links',
        ']' => 'vierkant haakje rechts',
        '{' => 'accolade links',
        '}' => 'accolade rechts',
        '<' => 'kleiner dan teken',
        '>' => 'groter dan teken',
        '|' => 'verticale streep',
        '°' => 'gradenteken',
        '*' => 'asterisk',
        '+' => 'plusteken',
        '=' => 'is-gelijk-teken',
        '#' => 'hekje',
        '§' => 'paragraafsymbool',
        '$' => 'dollarteken',
        '€' => 'euroteken',
        '~' => 'tilde',
        '_' => 'underscore',
        '%' => 'procentteken',
        '^' => 'dakje',
        'é' => 'e accent aigu',
        'è' => 'e accent grave',
        'ë' => 'e trema',
        'ê' => 'e accent circonflexe',
        'õ' => 'o tilde',
        'ø' => 'o schuine streep',
        );

    $ret = array();
    $arr = str_split_unicode($s);
    foreach ($arr as $char) {
        $c = strtoupper($char);
        if (!isset($alph[$c])) $alph[$c] = $char; 
        $ret[] = $alph[$c];
    }

    return $ret;     
    
}
